import { Map } from './map';

export const CATEGORIES: Map[] = [
{key: 1, value: "Baby"},
{key: 2, value: "Beauty"},
{key: 3, value: "Food"},
{key: 4, value: "Garden"},
{key: 5, value: "Health"},
{key: 6, value: "Household"},
{key: 7, value: "International"},
{key: 8, value: "Pet"},
{key: 9, value: "Toys"},
{key: 10, value: "Wine & Beer"},
]

export const SUPPLIERS: Map[] = [
    
    {key: 1, value: "3M"},    
    {key: 2, value: "Abbott Medical Optics, Inc."},
    {key: 3, value: "Abbott Nutrition"},
    {key: 4, value: "ACH Food Companies"},
    {key: 5, value: "Acme Smoked Fish Corp."},
    {key: 6, value: "Adria Imports Inc"},
    {key: 7, value: "Advanced Beauty Systems, Inc."},
    {key: 8, value: "Ahold USA, Inc."},
    {key: 9, value: "Aidells Sausage Co."},
    {key: 10, value: "Alberto-Culver USA, Inc."},
    {key: 11, value: "Alcon"},
    {key: 12, value: "B&G Foods"},
    {key: 13, value: "Bausch & Lomb Pharmaceuticals, Inc."},
    {key: 14, value: "Bausch + Lomb"},
    {key: 15, value: "Bayer HealthCare Consumer Care"},
    {key: 16, value: "Bendon Publishing International"},
    {key: 17, value: "BIC USA Inc."},
    {key: 18, value: "Bimbo Bakeries USA, Inc."},
    {key: 19, value: "C.H. Guenther & Son, Inc."},
    {key: 20, value: "Campbell Soup Company"},
    {key: 21, value: "CCA Industries Inc."},
    {key: 22, value: "Chattem, Inc."},
    {key: 23, value: "Church & Dwight Co., Inc."},
    {key: 24, value: "Colgate-Palmolive Company"},
    {key: 25, value: "ConAgra Foods Inc."},
    {key: 26, value: "Cumberland Packing Corp."},
    {key: 27, value: "Daniele, Inc."},
    {key: 28, value: "DCI Cheese Company, Inc."},
    {key: 29, value: "Dean Foods Company"},
    {key: 30, value: "Del Monte Pet Products"},
    {key: 31, value: "Diamond Foods, Inc."},
    {key: 32, value: "Dr. Pepper Snapple Group"},
    {key: 33, value: "Dr. Pepper/Seven Up, Inc."},
    {key: 34, value: "Ducere Pharma"},
    {key: 35, value: "E&J Gallo Winery"},
    {key: 36, value: "Eastland Food Corporation, Inc."},
    {key: 37, value: "Edward & Sons Trading"},
    {key: 38, value: "Elmer's Products, Inc."},
    {key: 39, value: "Energizer Personal Care"},
    {key: 40, value: "F.M. Brown's Sons Inc."},
    {key: 41, value: "Farley's & Sathers Candy Company, Inc."},
    {key: 42, value: "Ferrero U.S.A., Incorporated"},
    {key: 43, value: "Freeman Cosmetics"},
    {key: 44, value: "Frito-Lay, Inc."},
    {key: 45, value: "Funko, LLC"},
    {key: 46, value: "Garnier Inc."},
    {key: 47, value: "General Mills, Inc."},
    {key: 48, value: "Glaxosmithkline Consumer Healthcare, Lp."},
    {key: 49, value: "Green Mountain Coffee, Inc."},
    {key: 50, value: "H.J. Heinz Company"},
    {key: 51, value: "Hanesbrands Inc"},
    {key: 52, value: "Hasbro"},
    {key: 53, value: "Hormel Foods Corporation"},
    {key: 54, value: "i-Health, Inc."},
    {key: 55, value: "Imperial Toy Corporation"},
    {key: 56, value: "JFC International Inc."},
    {key: 57, value: "Johnson & Johnson"},
    {key: 58, value: "Kashi International Corporation"},
    {key: 59, value: "Kellogg Company"},
    {key: 60, value: "Kimberly-Clark Global Sales, LLC."},
    {key: 61, value: "Kraft Foods, Inc."},
]
